version: '3'
services:
  omada-controller:
    build: .
    network_mode: host
    volumes:
      - /opt/tplink/EAPController/data
      - /opt/tplink/EAPController/work
      - /opt/tplink/EAPController/logs
    ports:
      - "8088:8088"
      - "8043:8043"
    restart: "always"
    privileged: true
